[v1]
"amp 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"bat 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"checkpwn 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["checkpwn"]
"du-dust 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"fastmod 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fastmod"]
"fd-find 8.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-delta 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hck 0.5.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["hck"]
"hexyl 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"hyperfine 1.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"mdbook 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"natls 2.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["natls"]
"nu 0.35.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_core_fetch", "nu_plugin_core_match", "nu_plugin_core_post", "nu_plugin_core_ps", "nu_plugin_core_sys"]
"pepper 0.10.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["pepper"]
"pipes-rs 1.4.4 (git+https://github.com/lhvy/pipes-rs#c49b70743b1cfcd92301f738e627162c0fc370bb)" = ["pipes-rs"]
"procs 0.11.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rnr 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr"]
"rocketfetch 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["rocketfetch"]
"rust-passmaker 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rust-passmaker"]
"rustscan 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"skim 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"speedtest-rs 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"starship 0.56.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tiny 0.9.0 (git+https://github.com/osa1/tiny.git#1ace59078c4edf226ea7e52c041d626a0adb605c)" = ["tiny"]
"tock 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tock"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tree-rs 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["tree-rs"]
"xcp 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"xh 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xh"]
"yaydl 0.6.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["yaydl"]
"zellij 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
