path = ["/usr/local/Homebrew/bin", "/usr/bin", "/bin", "/Users/trevoropiyo/.cargo/bin"]
prompt = "STARSHIP_SHELL= starship prompt"
startup = ["zoxide init nushell --hook prompt | save ~/.zoxide.nu", "source ~/.zoxide.nu"]
skip_welcome_message = true
[env]
CMD_DURATION_MS = "38"
HOME = "/Users/trevoropiyo"
LANG = "en_US.UTF-8"
LOGNAME = "trevoropiyo"
SHELL = "/Users/trevoropiyo/.cargo/bin/nu"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.PpYlZmOzFb/Listeners"
TERM = "xterm-256color"
TERM_PROGRAM = "Apple_Terminal"
TERM_PROGRAM_VERSION = "440"
TERM_SESSION_ID = "51C0514B-D665-400E-950C-42816F038643"
TMPDIR = "/var/folders/9s/0m6x4p995bbgjfy9h6jp1tvr0000gn/T/"
USER = "trevoropiyo"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
__CFBundleIdentifier = "com.apple.Terminal"
__CF_USER_TEXT_ENCODING = "0x1F5:0x0:0x0"
