[v1]
"amp 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"bat 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"du-dust 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fastmod 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fastmod"]
"fd-find 8.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-delta 0.11.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hyperfine 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 0.10.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"lsd 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"mdbook 0.4.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"natls 2.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["natls"]
"nu 0.41.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_core_inc", "nu_plugin_core_match", "nu_plugin_core_textview", "nu_plugin_extra_binaryview", "nu_plugin_extra_chart_bar", "nu_plugin_extra_chart_line", "nu_plugin_extra_from_bson", "nu_plugin_extra_from_sqlite", "nu_plugin_extra_query_json", "nu_plugin_extra_s3", "nu_plugin_extra_selector", "nu_plugin_extra_start", "nu_plugin_extra_to_bson", "nu_plugin_extra_to_sqlite", "nu_plugin_extra_tree", "nu_plugin_extra_xpath"]
"pipes-rs 1.4.6 (git+https://github.com/lhvy/pipes-rs#84c9e2e824188a95429cf3e89bc3dc4054207c93)" = ["pipes-rs"]
"procs 0.11.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rnr 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr"]
"rocketfetch 0.5.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["rocketfetch"]
"rust-passmaker 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rust-passmaker"]
"rustscan 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"skim 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"speedtest-rs 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"starship 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tiny 0.10.0 (git+https://github.com/osa1/tiny.git#2c723f6b46f6ea8210290f1d6a627a607668dcb1)" = ["tiny"]
"tock 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tock"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tree-rs 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["tree-rs"]
"xcp 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"xh 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xh"]
"zellij 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.7.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
