[v1]
"amp 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"bat 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 8.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"comrak 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["comrak"]
"du-dust 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fastmod 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fastmod"]
"fd-find 8.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"git-delta 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hyperfine 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 0.10.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"lsd 0.21.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"mdbook 0.4.15 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"mdcat 0.25.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdcat"]
"natls 2.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["natls"]
"nu 0.43.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_core_match"]
"pepper 0.22.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["pepper"]
"procs 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rnr 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr"]
"rocketfetch 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["rocketfetch"]
"rustscan 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"skim 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"starship 1.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tiny 0.10.0 (git+https://github.com/osa1/tiny#2c723f6b46f6ea8210290f1d6a627a607668dcb1)" = ["tiny"]
"tock 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tock"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tree-rs 0.6.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["tree-rs"]
"xcp 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"xh 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xh"]
"zellij 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
