[v1]
"amp 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["amp"]
"bat 0.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"checkpwn 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["checkpwn"]
"du-dust 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"dua-cli 2.14.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["dua"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"ferris-fetch 1.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["ferris-fetch"]
"git-delta 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"hck 0.5.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["hck"]
"hexyl 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hexyl"]
"hyperfine 1.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"just 0.10.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"kibi 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["kibi"]
"lsd 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["lsd"]
"mdbook 0.4.12 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"natls 2.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = ["natls"]
"nu 0.34.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["nu", "nu_plugin_core_fetch", "nu_plugin_core_match", "nu_plugin_core_post", "nu_plugin_core_ps", "nu_plugin_core_sys"]
"ox 0.2.7 (git+https://github.com/curlpipe/ox#086f66532f053c0feeffa94b92b9ebfd3e9feb33)" = ["ox"]
"pepper 0.11.0 (git+https://github.com/vamolessa/pepper#7de5ae35c1316193b776825568117d86e0244ea2)" = ["pepper"]
"pipes-rs 1.4.4 (git+https://github.com/lhvy/pipes-rs#286e11089c0a227d5d4030605e9ad207a01fe71f)" = ["pipes-rs"]
"procs 0.11.9 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rnr 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rnr"]
"rocketfetch 0.5.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["rocketfetch"]
"rustscan 2.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rustscan"]
"skim 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"speedtest-rs 0.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["speedtest-rs"]
"starship 0.56.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tealdeer 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tiny 0.9.0 (git+https://github.com/osa1/tiny.git#1ace59078c4edf226ea7e52c041d626a0adb605c)" = ["tiny"]
"tock 0.1.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["tock"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"xcp 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xcp"]
"xh 0.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["xh"]
"yaydl 0.6.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["yaydl"]
"zellij 0.15.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zellij"]
"zoxide 0.7.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
