# Servers to auto-connect
servers:
    - addr: irc.oftc.net
      port: 6697
      tls: true

      # (optional) Server alias for display in tab line
      alias: OFTC

      # Channels to automatically join
      join:
          - "#tiny"
    - addr: irc.libera.chat
      port: 6697
      tls: true

      # (optional) Server alias for display in tab line
      alias: LIBERA

      # Channels to automatically join
      join:
          - "#libera"
          - "##rust"
          - "#unixporn"
          - "#go-nuts"

      # Three authentication methods: pass, sasl, and nickserv_ident
      # These are optional and you probably only need one of these, delete
      # others.


      # SASL authentication
      # sasl:
      #   username: 'tiny_user'
      #   password: 'hunter2'

      # Identify nick by sending a message to NickServ:
      # (useful when `pass` or `sasl` fields above are not used)
      # nickserv_ident: 'hunter2'

# Defaults used when connecting to servers via the /connect command
defaults:
    join: []
    tls: true
    
# Where to put log files
#log_dir: "{}"

# (Optional) Limits the maximum number of messages stored for each UI tab. Defaults to unlimited.
# scrollback: 512

# (Optional) UI layout: 'compact' or 'aligned'. Defaults to 'compact'.
layout: aligned

# (Optional) Nick length in 'aligned' layout. Default is 12.
# max_nick_length: 12

# Color theme based on 256 colors. Colors can be defined as color indices
# (0-255) or ith their names.
