tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "python@3.9"
brew "curl"
brew "dotnet"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "go"
brew "ipfs"
brew "libressl"
brew "libssh"
brew "llvm"
brew "lua"
brew "mas"
brew "mono"
brew "openjdk"
brew "openssh"
brew "openssl@3"
brew "pandoc"
brew "publish"
brew "ruby"
brew "rustup-init"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "alacritty"
cask "amethyst"
cask "coderunner"
cask "discord-canary"
cask "macs-fan-control"
cask "zoom"
mas "Boop", id: 1518425043
mas "Codye", id: 1516894961
mas "Developer", id: 640199958
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Dynamo", id: 1445910651
mas "HazeOver", id: 430798174
mas "Hush", id: 1544743900
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LanguageTool", id: 1534275760
mas "Magic Lasso", id: 1198047227
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "TestFlight", id: 899247664
mas "Twitter", id: 1482454543
mas "Vinegar", id: 1591303229
